{
  "formatVersion": "1.1",
  "component": {
    "group": "be.kuleuven",
    "module": "scorebord",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "scorebord-1.0-SNAPSHOT.jar",
          "url": "scorebord-1.0-SNAPSHOT.jar",
          "size": 284635,
          "sha512": "ad31c35b7a474deadb088a7ad70faea67d5ed4b7932e8cbe8a160d95e31e423ed2f819ab58478e8eb58c9b225f5c8fb4b80c4f7965333b22bdf922582f2b5b41",
          "sha256": "cbb90c82a9558636928aa39ef9089165738c2519940e9ba5d453b23a529b6744",
          "sha1": "2a5f26c444c10b1e15815763060c8474aa963981",
          "md5": "ed2e6541a4f1e31d30028a0d51def1a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "scorebord-1.0-SNAPSHOT.jar",
          "url": "scorebord-1.0-SNAPSHOT.jar",
          "size": 284635,
          "sha512": "ad31c35b7a474deadb088a7ad70faea67d5ed4b7932e8cbe8a160d95e31e423ed2f819ab58478e8eb58c9b225f5c8fb4b80c4f7965333b22bdf922582f2b5b41",
          "sha256": "cbb90c82a9558636928aa39ef9089165738c2519940e9ba5d453b23a529b6744",
          "sha1": "2a5f26c444c10b1e15815763060c8474aa963981",
          "md5": "ed2e6541a4f1e31d30028a0d51def1a3"
        }
      ]
    }
  ]
}
